import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Menu, X } from 'lucide-react';
const Navbar = () => {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    return (_jsxs("nav", { className: "bg-white border-b border-gray-200 py-4", children: [_jsxs("div", { className: "container mx-auto px-4 flex justify-between items-center", children: [_jsx(Link, { to: "/", className: "flex items-center", children: _jsx("span", { className: "text-2xl font-bold text-blue-600", children: "StudyShare" }) }), _jsxs("div", { className: "hidden md:flex items-center space-x-8", children: [_jsx(Link, { to: "/", className: "text-gray-700 hover:text-blue-600 font-medium", children: "Home" }), _jsx(Link, { to: "/browse", className: "text-gray-700 hover:text-blue-600 font-medium", children: "Browse" }), _jsx(Link, { to: "/login", className: "text-gray-700 hover:text-blue-600 font-medium", children: "Login" }), _jsx(Link, { to: "/register", className: "bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors", children: "Register" })] }), _jsx("button", { className: "md:hidden text-gray-500 hover:text-gray-700 focus:outline-none", onClick: () => setIsMenuOpen(!isMenuOpen), children: isMenuOpen ? _jsx(X, { size: 24 }) : _jsx(Menu, { size: 24 }) })] }), isMenuOpen && (_jsx("div", { className: "md:hidden bg-white px-4 py-2 shadow-lg absolute top-16 inset-x-0 z-50", children: _jsxs("div", { className: "flex flex-col space-y-4 py-4", children: [_jsx(Link, { to: "/", className: "text-gray-700 hover:text-blue-600 font-medium", onClick: () => setIsMenuOpen(false), children: "Home" }), _jsx(Link, { to: "/browse", className: "text-gray-700 hover:text-blue-600 font-medium", onClick: () => setIsMenuOpen(false), children: "Browse" }), _jsx(Link, { to: "/login", className: "text-gray-700 hover:text-blue-600 font-medium", onClick: () => setIsMenuOpen(false), children: "Login" }), _jsx(Link, { to: "/register", className: "bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors inline-block text-center", onClick: () => setIsMenuOpen(false), children: "Register" })] }) }))] }));
};
export default Navbar;
